# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  CoffeeCupEngine_config = debug
endif
ifeq ($(config),release)
  CoffeeCupEngine_config = release
endif

PROJECTS := CoffeeCupEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CoffeeCupEngine:
ifneq (,$(CoffeeCupEngine_config))
	@echo "==== Building CoffeeCupEngine ($(CoffeeCupEngine_config)) ===="
	@${MAKE} --no-print-directory -C CoffeeCupEngine -f Makefile config=$(CoffeeCupEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C CoffeeCupEngine -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CoffeeCupEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"